### ISSUE TITLE
secure token?

### ISSUE THREAD

**Issue by siddo420** [fereidani/recaptcha2#1]
Does it work with secure tokens feature?

https://developers.google.com/recaptcha/docs/secure_token

**Comment by fereidani** [comment]
Thank you for submitting this issue ,
Currently this feature is not supported ,
I will work on it if i got any free time .
Pull requests are welcome , but please specify an api that promise backward compatibility before sending PRs.

**Comment by fereidani** [comment]
https://developers.google.com/recaptcha/docs/secure_token
secure token is a deprecated feature .
