### ISSUE TITLE
Switch from request to got

### ISSUE THREAD

**Issue by adityapatadia** [fereidani/recaptcha2#12]
This is much better and lightweight library for making requests: https://www.npmjs.com/package/got
It also supports promises out of the box. It would be great if we can switch to this one.

**Comment by fereidani** [comment]
Hi, it seems nice library, but recaptcha2 depend on request and tested for a long enough time with it, i'm afraid changing to `got` introduces new problems so i prefer to keep things same as they are now, at least for now.
maybe someday if somebody report performance problem we'll migrate to `got` or native nodejs api.
but for now, any change in this area is unnecessary.

**Comment by adityapatadia** [comment]
https://github.com/request/request/issues/3142
