### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by zoozlerDev** [fereidani/recaptcha2#3]
It seems like error handler in recaptcha2 doesn't really send error, but just a normal response.

**Comment by fereidani** [comment]
could you please describe whole scenario of this issue . i don't understand your point .

**Comment by zoozlerDev** [comment]
The error message sent from recaptcha.translateErrors(err) does not act like an error, but just a normal response. Does it make sense for you?

**Comment by zoozlerDev** [comment]
So now in addition to error handler on my front-end, I have to implement additional coding to check if my response is ["missing-input-secret"] and fire an error.

**Comment by fereidani** [comment]
as you can see in : 
https://developers.google.com/recaptcha/docs/verify
google returns cause of error as a standard string , you can check Error code reference section .
in this library translateErrors method just translate error codes to human readable text and does not throw exception or anything special.
errors handled in promise catch so it's not classic try catch exception .
if you need errors as exception you can use javascript generators and yield library promise .

**Comment by zoozlerDev** [comment]
I see. Thank you for your clear and details answer!
