### ISSUE TITLE
send response key with ajax

### ISSUE THREAD

**Issue by VassilisPallas** [fereidani/recaptcha2#5]
Hello,
I'm getting response with ajax, and the `recaptcha.validate` goes to catch, with `undefined` error.
backend:
```
recaptcha = new reCAPTCHA({
    siteKey: config.siteKey,
    secretKey: config.secretKey
});

router.post('/change-password-post', function (req, res) {
    console.log(req.body);
    var result = '';
    var type = 'success';
    var key = req.body.response;

    recaptcha.validate(key)
        .then(function () {
           // do something
            result = 'good!';
            return res.send({type: type, result: result});
        })
        .catch(function (err) {
            console.log(err);
            console.log(recaptcha.translateErrors(err));
            type = 'error';
            return res.send({type: type, result: result});
        });
});
```

and the data in ajax call

```
data: {
    response: $('#g-recaptcha-response').val()
 }
```

Is this the correct response textArea? An if yes why it can't verify it. Is there anything else I have to set?

**EDIT**
The error says `The response parameter is missing.The secret parameter is missing.` I changed `validate(key)` to `validateRequest(req) `, and ajax data to `'g-recaptcha-response': $('#g-recaptcha-response').val()`. Why it throws this error?

**Comment by fereidani** [comment]
Hi , 
are you sure your response in ajax call reach the node side ?

**Comment by VassilisPallas** [comment]
Hi,
yes the response is the same with the `g-recaptcha-response` value
