### ISSUE TITLE
not exactly sure how to use when injecting into frontend

### ISSUE THREAD

**Issue by victorbadila** [fereidani/recaptcha2#6]
Hi,

I was looking at this module and I tried using it inside an angular1 app. I installed the module, injected it via browserify and I was able to render the captcha iframe via the `formElement` method. However I looked at your module internally and it only exposes a method for validating things programmatically (via the `validate` method). I couldn't find any functionality for getting the callback for when a user clicks the recaptcha on the frontend. 
Is what I'm trying to do against the purpose of this module and is it only supposed to validate requests server side and not on the front end only on events triggered by users?

Best,

**Comment by fereidani** [comment]
Hi , those functions handles on google client and server side script and there is no need for callback,
put element on form , user will complete it and submit the form then process form validity on your server via library methods. 
no programming action required on your client side.

**Comment by victorbadila** [comment]
Ok, I get it. My curiosity was if I was able to validate this only between `front end --> Google`, and based on the result have an action execute, maybe enable a disabled form submission button, or something like that. I would like to keep my server agnostic of any captcha validity concerns.

**Comment by fereidani** [comment]
so if user saying ok google said i'm good boy how you could ensure that he is ?
final captcha verification should be done on server side to ensure request authority.
