### ISSUE TITLE
Response is not defined: Reference error

### ISSUE THREAD

**Issue by bnadeem** [fereidani/recaptcha2#7]
Hi, I have the following code in node.js on server side

 var recaptcha = new recaptcha2({
  siteKey:config.app.recaptcha.siteKey,
  secretKey: config.app.recaptcha.secretKey
});

recaptcha.validate(req.body.g-recaptcha-response)

I'm wondering why I'm getting the "response is not defined error:

Thanks

**Comment by fereidani** [comment]
Hi ,
You have semantic error  in your code
You are sending  `req.body.g - recaptcha - response` to validate, correct is `req.body['g-recaptcha-response']`

Regards
